export const CgPageShell = ({children}:any) => <div>{children}</div>;
export const CgAlert = ({children}:any) => <div>{children}</div>;
export const CgEmptyState = () => null;
export const CgSelect = () => null;

export * from './Avatar';
export * from './Badge';
export * from './Button';
export * from './CgBarChart';
export * from './DataTable';
export * from './DatePicker';
export * from './FilterToolbar';
export * from './MetricCard';
export * from './Modal';
export * from './PageHeader';
export * from './Progress';
export * from './RecentActivityTable';
export * from './SearchableSelect';
export * from './SectionPanel';
export * from './Tabs';
export * from './CgPieChart';
export * from './CgLineChart';
