-- LEAVE MANAGEMENT MODULE UPGRADE
-- Run this in Supabase SQL Editor

-- 1. Safely add new columns to leave_requests (without IF NOT EXISTS which can fail on serials)
DO $$ 
BEGIN 
  BEGIN
    ALTER TABLE leave_requests ADD COLUMN leave_type TEXT DEFAULT 'casual' CHECK (leave_type IN ('quick', 'casual', 'sick', 'long'));
  EXCEPTION WHEN duplicate_column THEN END;

  BEGIN
    ALTER TABLE leave_requests ADD COLUMN day_type TEXT DEFAULT 'full' CHECK (day_type IN ('full', 'first_half', 'second_half'));
  EXCEPTION WHEN duplicate_column THEN END;

  BEGIN
    ALTER TABLE leave_requests ADD COLUMN from_date DATE;
  EXCEPTION WHEN duplicate_column THEN END;

  BEGIN
    ALTER TABLE leave_requests ADD COLUMN to_date DATE;
  EXCEPTION WHEN duplicate_column THEN END;

  BEGIN
    ALTER TABLE leave_requests ADD COLUMN total_days DECIMAL(4,1) DEFAULT 1;
  EXCEPTION WHEN duplicate_column THEN END;

  BEGIN
    ALTER TABLE leave_requests ADD COLUMN auto_message TEXT;
  EXCEPTION WHEN duplicate_column THEN END;

  BEGIN
    ALTER TABLE leave_requests ADD COLUMN attachment_url TEXT;
  EXCEPTION WHEN duplicate_column THEN END;

  BEGIN
    ALTER TABLE leave_requests ADD COLUMN doc_no BIGINT GENERATED BY DEFAULT AS IDENTITY;
  EXCEPTION WHEN duplicate_column THEN END;
END $$;

-- Migrate existing `date` → `from_date` and `to_date`
UPDATE leave_requests SET from_date = date::DATE, to_date = date::DATE WHERE from_date IS NULL;

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_leave_requests_student ON leave_requests(student_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_teacher ON leave_requests(teacher_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_leave_requests_type ON leave_requests(leave_type);

-- EXAMINATION MODULE TABLES
CREATE TABLE IF NOT EXISTS exams (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  org_id TEXT NOT NULL,
  exam_name TEXT NOT NULL,
  type TEXT DEFAULT 'college' CHECK (type IN ('school', 'college')),
  status TEXT DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'active', 'past', 'draft')),
  date_from DATE,
  date_to DATE,
  exam_fee DECIMAL(10,2) DEFAULT 0,
  fee_enabled BOOLEAN DEFAULT false,
  pdf_url TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS exam_timetable_entries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  exam_id UUID NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  subject TEXT NOT NULL,
  exam_date DATE NOT NULL,
  day_of_week TEXT,
  start_time TEXT,
  end_time TEXT,
  room TEXT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS exam_fees (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  exam_id UUID NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status TEXT DEFAULT 'unpaid' CHECK (status IN ('paid', 'unpaid')),
  paid_at TIMESTAMPTZ,
  payment_ref TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (exam_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_exams_org ON exams(org_id);
CREATE INDEX IF NOT EXISTS idx_exam_entries_exam ON exam_timetable_entries(exam_id);
CREATE INDEX IF NOT EXISTS idx_exam_entries_date ON exam_timetable_entries(exam_date);
CREATE INDEX IF NOT EXISTS idx_exam_fees_student ON exam_fees(student_id);

-- RLS Enable
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_timetable_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_fees ENABLE ROW LEVEL SECURITY;

-- Safely drop old policies if they exist so we don't get 'policy already exists' errors
DO $$ 
BEGIN
  -- Exams
  DROP POLICY IF EXISTS "exams_read_all" ON exams;
  DROP POLICY IF EXISTS "exams_insert_service" ON exams;
  DROP POLICY IF EXISTS "exams_update_service" ON exams;
  DROP POLICY IF EXISTS "exams_delete_service" ON exams;
  
  -- Entries
  DROP POLICY IF EXISTS "exam_entries_read_all" ON exam_timetable_entries;
  DROP POLICY IF EXISTS "exam_entries_insert_service" ON exam_timetable_entries;
  DROP POLICY IF EXISTS "exam_entries_update_service" ON exam_timetable_entries;
  DROP POLICY IF EXISTS "exam_entries_delete_service" ON exam_timetable_entries;

  -- Fees
  DROP POLICY IF EXISTS "exam_fees_read_all" ON exam_fees;
  DROP POLICY IF EXISTS "exam_fees_insert_service" ON exam_fees;
  DROP POLICY IF EXISTS "exam_fees_update_service" ON exam_fees;
END $$;

-- Create Policies (Using 'true' for MVP so your backend can insert without failing due to RLS)
CREATE POLICY "exams_read_all" ON exams FOR SELECT USING (true);
CREATE POLICY "exams_insert_service" ON exams FOR INSERT WITH CHECK (true);
CREATE POLICY "exams_update_service" ON exams FOR UPDATE USING (true);
CREATE POLICY "exams_delete_service" ON exams FOR DELETE USING (true);

CREATE POLICY "exam_entries_read_all" ON exam_timetable_entries FOR SELECT USING (true);
CREATE POLICY "exam_entries_insert_service" ON exam_timetable_entries FOR INSERT WITH CHECK (true);
CREATE POLICY "exam_entries_update_service" ON exam_timetable_entries FOR UPDATE USING (true);
CREATE POLICY "exam_entries_delete_service" ON exam_timetable_entries FOR DELETE USING (true);

CREATE POLICY "exam_fees_read_all" ON exam_fees FOR SELECT USING (true);
CREATE POLICY "exam_fees_insert_service" ON exam_fees FOR INSERT WITH CHECK (true);
CREATE POLICY "exam_fees_update_service" ON exam_fees FOR UPDATE USING (true);
