name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'



      - name: SSH and Deploy Backend
        uses: appleboy/ssh-action@master
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: PRODUCTION_ENV
          script: |
            cd /var/www/classgrid_platform
            
            # Pull the latest code from GitHub
            git fetch origin main
            git reset --hard origin/main
            
            # Go into server folder, install new packages, and restart PM2
            cd server
            echo "$PRODUCTION_ENV" > .env
            npm install --omit=dev
            pm2 restart all


